replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: false

pdb:
  enabled: false

ingress:
  enabled: false

serviceMonitor:
  enabled: true
  additionalLabels:
    release: kube-prometheus-stack
